//! Stable IDs are the routing contract. Never persist a menu index.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ToolId {
    Documents,
    Json,
    Crypto,
    Diff,
    Images,
    Archives,
    Codes,
    Cleanup,
    Clipboard,
}

pub struct ToolDescriptor {
    pub id: ToolId,
    pub key: &'static str,
    pub name: &'static str,
    pub subtitle: &'static str,
    pub libraries: &'static str,
    pub capabilities: &'static str,
    pub available: bool,
}

pub const TOOLS: &[ToolDescriptor] = &[
    ToolDescriptor {
        id: ToolId::Documents,
        key: "documents",
        name: "Document converter",
        subtitle: "Turn everyday documents into clean Markdown.",
        libraries: "anydoc",
        capabilities: "Local document parsing · Markdown source · Copy and export",
        available: true,
    },
    ToolDescriptor {
        id: ToolId::Json,
        key: "json",
        name: "JSON workbench",
        subtitle: "Make structured data easier to read and transform.",
        libraries: "jaq",
        capabilities: "Format and validate JSON\nQuery, filter and transform with jq syntax\nInspect and export results",
        available: true,
    },
    ToolDescriptor {
        id: ToolId::Crypto,
        key: "crypto",
        name: "Hash & encrypt",
        subtitle: "Verify file integrity and protect local data.",
        libraries: "sha2 + age",
        capabilities: "SHA-256 / SHA-512 checksums and verification\nage file encryption and decryption\nPassphrase and recipient public key modes",
        available: true,
    },
    ToolDescriptor {
        id: ToolId::Diff,
        key: "diff",
        name: "Text diff",
        subtitle: "See exactly what changed between two versions.",
        libraries: "similar",
        capabilities: "Compare text and files side by side\nLine differences and change summaries\nExport unified diffs",
        available: true,
    },
    ToolDescriptor {
        id: ToolId::Images,
        key: "images",
        name: "Image studio",
        subtitle: "Resize, convert and inspect your images locally.",
        libraries: "image + fast_image_resize + oxipng + nom-exif",
        capabilities: "Image conversion and batch resizing\nLossless PNG optimization\nEXIF metadata inspection",
        available: false,
    },
    ToolDescriptor {
        id: ToolId::Archives,
        key: "archives",
        name: "Archives",
        subtitle: "Pack, inspect and unpack your files.",
        libraries: "zip + sevenz-rust2",
        capabilities: "Create and extract ZIP / 7z archives\nPreview archive contents\nValidate paths and limit extraction size",
        available: false,
    },
    ToolDescriptor {
        id: ToolId::Codes,
        key: "codes",
        name: "Barcode reader",
        subtitle: "Read QR codes and barcodes from images.",
        libraries: "rxing",
        capabilities: "Decode QR codes and common barcodes\nImport images and inspect results\nCopy decoded text",
        available: true,
    },
    ToolDescriptor {
        id: ToolId::Cleanup,
        key: "cleanup",
        name: "Disk cleanup",
        subtitle: "Find duplicates and reclaim disk space.",
        libraries: "czkawka_core",
        capabilities: "Find duplicate, empty and large files\nDiscover similar images\nPreview and confirm before cleaning up",
        available: false,
    },
    ToolDescriptor {
        id: ToolId::Clipboard,
        key: "clipboard",
        name: "Clipboard",
        subtitle: "A temporary workspace for the things you copy.",
        libraries: "clipboard-rs",
        capabilities: "Inspect text, images and file references\nCollect and copy items manually\nOpt-in session history",
        available: false,
    },
];
